[package]
name = "elikar"
version = "0.1.0"
authors = ["xstater <l>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2-sys = "0.34.3"
libc = "0.2.77"
xrsignal = { version = "0.1.1", git = "https://github.com/xstater/xrsginal" }


[profile.dev]
opt-level = 2
debug = false
lto = false
panic = "abort"

[profile.release]
opt-level = 2
debug = false
lto = false
panic = "abort"


[profile.test]
opt-level = 2
debug = false
lto = false

