[package]
name = "elikar"
version = "0.1.0"
authors = ["xstater <l>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2-sys = "0.34.3"
libc = "0.2.77"
elikar-gl = { version = "0.1.0", git = "https://github.com/xstater/elikar-gl"}
xecs = "0.2.10"
xrunits = "0.1.2"
xblend = "0.1.0"
ash = "0.33.0"
rand = "0.8.4"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 2
debug = false
lto = false

[lib]
name = "elikar"
crate-type = ["rlib","dylib"]